### ISSUE TITLE
Doesn't push external video to AgoraSDK

### ISSUE THREAD

**Issue by tomosia-phuongvo** [DeepARSDK/videocall-ios-swift#2]
I have been downloaded this project and build it on a real device. But I found an issue when using it with AgoraSDK. DeepAR SDK didn't callback pixel frames to delegate. So other devices couldn't see a remote video when calling the video

Please support me about this issue

Thank you!

**Comment by Sikter** [comment]
Hi, we have released new DeepAR SDK in the meantime and have upgraded the example to work with latest DeepAR SDK version. can you try that now. Also make sure to download the latest Agora SDK 3.1 I think it is.
This example will work with 2 physical devices as it is setup now.
